data:
        image: busybox
        volumes:
                - /var/lib/postgresql/data
datawar:
        image: busybox
        volumes:
                - /path/to/aqrsystem.war:/tmp/ROOT.war
dbinitdata:
    image: eeacms/ubuntu
    volumes:
        - /tmp/postgres_init_db_files/
    command: sh -c "mkdir -p /tmp/postgres_init_db_files && curl -L https://github.com/eea/aqr-public/raw/master/Database/create_aqd.sql>/tmp/postgres_init_db_files/create_aqd.sql && curl -L https://github.com/eea/aqr-public/raw/master/Database/insert_aqd.sql>/tmp/postgres_init_db_files/insert_aqd.sql && curl -L https://github.com/eea/aqr-public/raw/master/Database/UK_demos.sql>/tmp/postgres_init_db_files/UK_demos.sql"
    
database:
        name: database
        image: postgres:9.3
        env_file:
                - .secret
        volumes_from:
                - data
                - dbinitdata

server:
        image: eeacms/aqr-public
        links:
                - database:DB
        ports:
                - 8080:8080
        volumes_from:
                - datawar
